window.FILTERS = [

  "X-Ray Scan",
  "Banknote Engraving",
  "Wire Photo",
  "Giallo Gels",
  "Two-Strip",
  "Aerochrome",
  "Slow Shutter",
  "Full Stitch",
  "Aura Gradient",
  "Night Vision",
  "Blue Negative",
  "LED Matrix",
  "Chemical Frost",
  "Ink Bloom",
  "Photogram",
  "Heat Trace",
  "Scan Lines",
  "Film Soup",
  "Cyanotype",
  "Fogged Glass",
  "Dead Pixels",
  "Low Poly",
  "256 Colors",
  "Blue Flood",
  "Herbarium",
  "Density Map",
  "Thermal Print",
  "Paint By Number",
  "Encyclopedia Plate",
  "Ransom Collage",
  "Wet Emulsion",
  "Desktop 98",
  "Cursor Swarm",
  "Cutout Redaction",
  "Scribble Riot",
  "Paper Crumple",
  "Solarized Print",
  "Marker Makeup",
  "Deadpan Toon",
  "Chirashi Flyer",
  "Street Poster",
  "Cross Stitch",
  "Blind Emboss",
  "Overprint",
  "Sticker Bomb",
  "Bubble Wrapped",
  "Liquid Chrome",
  "Specimen Sheet",
  "Misprint Echo",
  "Camcorder HUD",
  "VHS Chrome",
  "Split Halftone",
  "Indexed Dither",
  "Stencil Fluoro",
  "Sabattier Push",
  "Voxel Relief",
  "Amber Glamour",
  "Screen Engraving",
  "Thermal Liquid",
  "Fog Silhouette",
  "Pink Bloom",
  "Rescreen",
  "Teletext",
  "Redscale Flash",
  "Heat Negative",
  "Chromatography",
  "Vector Dissect",
  "Dragged Shutter",
  "Screen Clash",
  "Chemigram",
  "Expired Tungsten",
  "Pastel Thermal",
  "Paste-Up Collage",
  "Overexposure Bloom",
  "Slit Scan",
  "Platen Drag",
  "Blacklight",
  "Forensic Photo",
  "Lenticular",
  "Pinscreen",
  "Electron Scan",
  "Daguerreotype",
  "Autochrome",
  "Jacquard Weave",
  "4-Shade LCD",
  "Dye Halo",
  "Light Painted",
  "Edge Trace",
  "VCR OSD",
  "Surveillance Dossier",
  "Thermal Mask",
  "Projector Burn",
  "Riso Bloom",
  "Radiograph Zine",
  "Pixel Sort",
  "Archive Rot",
  "Three Inks",
  "Scrap Stitched",
  "Bleach Dye",
  "Stitch Chart",
  "Dot Interference",
  "Cyber Sigil",
  "Chrome Rorschach",
  "Heat Contour",
  "Pixel Lace",
  "Pink Phosphor",
  "Dropped Stitch",
  "Hyper Slice",
  "Bio HUD",
  "Poison Copy"

];

window.FILTERS = window.FILTERS.map((name, index) => ({
  id: index + 1,
  name: name,
  desc: "Experimental image transformation"
}));